# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [11]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [12]:
url = "https://books.toscrape.com/"

response = requests.get(url)
response.encoding = "utf-8"

print(response.status_code)

200

In [13]:
soup = BeautifulSoup(response.text, "html.parser")

In [14]:
soup.title

<title>
    All products | Books to Scrape - Sandbox
</title>

In [15]:
books = soup.find_all("article", class_="product_pod")

In [16]:
len(books)

20

In [17]:
first_book = books[0]

In [18]:
title = first_book.find("h3").find("a")["title"]
print(title)

A Light in the Attic

In [19]:
price_text = first_book.find("p", class_="price_color").get_text()
print(price_text)

£51.77

In [21]:
price = float(price_text.replace("£", " "))
print(price)

51.77

In [22]:
rating_classes = first_book.find("p", class_="star-rating")["class"]
print(rating_classes)

['star-rating', 'Three']

In [23]:
rating_word = rating_classes[1]
print(rating_word)

Three

In [24]:
rating_numbers = {"One": 1,"Two": 2,"Three": 3,"Four": 4,"Five": 5}

In [26]:
rating = rating_numbers[rating_word]
print(rating)

3

In [ ]:
min_rating = 4
max_price = 20

if rating >= min_rating and price <= max_price:
    print("Seleccionamos el libro")
else:
    print("El libro no cumple los filtros")

El libro no cumple los filtros

In [31]:
for book in books:
    title = book.find("h3").find("a")["title"]

    price_text = book.find("p", class_="price_color").get_text()
    price = float(price_text.replace("£", ""))

    rating_word = book.find("p", class_="star-rating")["class"][1]
    rating = rating_numbers[rating_word]

    if rating >= min_rating and price <= max_price:
        print(title, price, rating)

        book_link = book.find("h3").find("a")["href"]
        print(book_link)

Set Me Free 17.46 5
catalogue/set-me-free_988/index.html

In [32]:
book_url = "https://books.toscrape.com/" + book_link
print(book_url)

https://books.toscrape.com/catalogue/set-me-free_988/index.html

In [33]:
book_response = requests.get(book_url)
book_response.encoding = "utf-8"

print(book_response.status_code)

book_soup = BeautifulSoup(book_response.text, "html.parser")

200

In [34]:
product_table = book_soup.find("table")
print(product_table)

<table class="table table-striped">
<tr>
<th>UPC</th><td>ce6396b0f23f6ecc</td>
</tr>
<tr>
<th>Product Type</th><td>Books</td>
</tr>
<tr>
<th>Price (excl. tax)</th><td>£17.46</td>
</tr>
<tr>
<th>Price (incl. tax)</th><td>£17.46</td>
</tr>
<tr>
<th>Tax</th><td>£0.00</td>
</tr>
<tr>
<th>Availability</th>
<td>In stock (19 available)</td>
</tr>
<tr>
<th>Number of reviews</th>
<td>0</td>
</tr>
</table>

In [35]:
product_info = {}

for row in product_table.find_all("tr"):
    key = row.find("th").get_text()
    value = row.find("td").get_text()

    product_info[key] = value

upc = product_info["UPC"]
availability = product_info["Availability"]

print("UPC:", upc)
print("Disponibilidad:", availability)

UPC: ce6396b0f23f6ecc
Disponibilidad: In stock (19 available)

In [36]:
breadcrumb = book_soup.find("ul", class_="breadcrumb")
print(breadcrumb)

<ul class="breadcrumb">
<li>
<a href="../../index.html">Home</a>
</li>
<li>
<a href="../category/books_1/index.html">Books</a>
</li>
<li>
<a href="../category/books/young-adult_21/index.html">Young Adult</a>
</li>
<li class="active">Set Me Free</li>
</ul>

In [37]:
genre = breadcrumb.find_all("a")[2].get_text()
print(genre)

Young Adult

In [38]:
description_heading = book_soup.find("div", id="product_description")
print(description_heading)

<div class="sub-header" id="product_description">
<h2>Product Description</h2>
</div>

In [39]:
paragraphs = book_soup.find_all("p")

for paragraph in paragraphs:
    print(paragraph.get_text())
    print("---")

£17.46
---



        In stock (19 available)


---










---
Aaron Ledbetter’s future had been planned out for him since before he was born. Each year, the Ledbetter family vacation on Tybee Island gave Aaron a chance to briefly free himself from his family’s expectations. When he meets Jonas “Lucky” Luckett, a caricature artist in town with the traveling carnival, he must choose between the life that’s been mapped out for him, and Aaron Ledbetter’s future had been planned out for him since before he was born. Each year, the Ledbetter family vacation on Tybee Island gave Aaron a chance to briefly free himself from his family’s expectations. When he meets Jonas “Lucky” Luckett, a caricature artist in town with the traveling carnival, he must choose between the life that’s been mapped out for him, and the chance at true love. ...more
---







---
£20.66
---



        In stock


---







---
£13.99
---



        In stock


---







---
£52.15
---



        In stock


---







---
£22.60
---



        In stock


---







---
£17.93
---



        In stock


---







---
£33.34
---



        In stock


---

In [40]:
description = paragraphs[3].get_text().strip()
print(description)

Aaron Ledbetter’s future had been planned out for him since before he was born. Each year, the Ledbetter family vacation on Tybee Island gave Aaron a chance to briefly free himself from his family’s expectations. When he meets Jonas “Lucky” Luckett, a caricature artist in town with the traveling carnival, he must choose between the life that’s been mapped out for him, and Aaron Ledbetter’s future had been planned out for him since before he was born. Each year, the Ledbetter family vacation on Tybee Island gave Aaron a chance to briefly free himself from his family’s expectations. When he meets Jonas “Lucky” Luckett, a caricature artist in town with the traveling carnival, he must choose between the life that’s been mapped out for him, and the chance at true love. ...more

In [41]:
title = book_soup.find("h1").get_text()

price = float(product_info["Price (incl. tax)"].replace("£", ""))

rating_word = book_soup.find("p", class_="star-rating")["class"][1]
rating = rating_numbers[rating_word]

print(title, price, rating)

Set Me Free 17.46 5

In [42]:
book_data = {"UPC": upc,"Title": title,"Price (£)": price,"Rating": rating,"Genre": genre,"Availability": availability,"Description": description}

books_df = pd.DataFrame([book_data])

books_df

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock (19 available),Aaron Ledbetter’s future had been planned out ...

In [43]:
next_page = soup.find("li", class_="next")
print(next_page)

<li class="next"><a href="catalogue/page-2.html">next</a></li>

In [44]:
next_link = next_page.find("a")["href"]
next_url = "https://books.toscrape.com/" + next_link

print(next_url)

https://books.toscrape.com/catalogue/page-2.html

In [45]:
response_page2 = requests.get(next_url)
response_page2.encoding = "utf-8"

soup_page2 = BeautifulSoup(response_page2.text, "html.parser")

books_page2 = soup_page2.find_all("article", class_="product_pod")

print("Código de respuesta:", response_page2.status_code)
print("Libros encontrados:", len(books_page2))

Código de respuesta: 200
Libros encontrados: 20

In [46]:
print(soup_page2.find("li", class_="next"))

<li class="next"><a href="page-3.html">next</a></li>

In [47]:
next_link = soup_page2.find("li", class_="next").find("a")["href"]

if "catalogue/" in next_link:
    next_url = "https://books.toscrape.com/" + next_link
else:
    next_url = "https://books.toscrape.com/catalogue/" + next_link

print(next_url)

https://books.toscrape.com/catalogue/page-3.html

In [48]:
def scrape_books(min_rating, max_price):
    books_data = []
    url = "https://books.toscrape.com/"

    rating_numbers = {"One": 1,"Two": 2,"Three": 3,"Four": 4,"Five": 5}

    while True:
        print("Revisando:", url)

        response = requests.get(url)
        response.encoding = "utf-8"

        if response.status_code != 200:
            print("Error al descargar:", url)
            return None

        soup = BeautifulSoup(response.text, "html.parser")
        books = soup.find_all("article", class_="product_pod")

        for book in books:
            title = book.find("h3").find("a")["title"]

            price_text = book.find("p", class_="price_color").get_text()
            price = float(price_text.replace("£", ""))

            rating_word = book.find("p", class_="star-rating")["class"][1]
            rating = rating_numbers[rating_word]

            if rating >= min_rating and price <= max_price:
                book_link = book.find("h3").find("a")["href"]

                if "catalogue/" in book_link:
                    book_url = "https://books.toscrape.com/" + book_link
                else:
                    book_url = (
                        "https://books.toscrape.com/catalogue/" + book_link
                    )

                book_response = requests.get(book_url)
                book_response.encoding = "utf-8"

                if book_response.status_code != 200:
                    print("Error al descargar:", book_url)
                    return None

                book_soup = BeautifulSoup(book_response.text, "html.parser")

                product_table = book_soup.find("table")
                product_info = {}

                for row in product_table.find_all("tr"):
                    key = row.find("th").get_text().strip()
                    value = row.find("td").get_text().strip()
                    product_info[key] = value

                upc = product_info["UPC"]
                availability = product_info["Availability"]

                breadcrumb = book_soup.find("ul", class_="breadcrumb")
                genre = breadcrumb.find_all("a")[2].get_text().strip()
                description = ""
                description_heading = book_soup.find("div", id="product_description")

                if description_heading is not None:
                    paragraphs = book_soup.find_all("p")
                    description = paragraphs[3].get_text().strip()
                books_data.append({"UPC": upc,"Title": title,"Price (£)": price,"Rating": rating,"Genre": genre,"Availability": availability,"Description": description})

        next_page = soup.find("li", class_="next")

        if next_page is None:
            break

        next_link = next_page.find("a")["href"]

        if "catalogue/" in next_link:
            url = "https://books.toscrape.com/" + next_link
        else:
            url = "https://books.toscrape.com/catalogue/" + next_link

    columns = ["UPC", "Title", "Price (£)", "Rating","Genre", "Availability", "Description"]

    return pd.DataFrame(books_data, columns=columns)

In [49]:
books_df = scrape_books(min_rating=4, max_price=20)

Revisando: https://books.toscrape.com/
Revisando: https://books.toscrape.com/catalogue/page-2.html
Revisando: https://books.toscrape.com/catalogue/page-3.html
Revisando: https://books.toscrape.com/catalogue/page-4.html
Revisando: https://books.toscrape.com/catalogue/page-5.html
Revisando: https://books.toscrape.com/catalogue/page-6.html
Revisando: https://books.toscrape.com/catalogue/page-7.html
Revisando: https://books.toscrape.com/catalogue/page-8.html
Revisando: https://books.toscrape.com/catalogue/page-9.html
Revisando: https://books.toscrape.com/catalogue/page-10.html
Revisando: https://books.toscrape.com/catalogue/page-11.html
Revisando: https://books.toscrape.com/catalogue/page-12.html
Revisando: https://books.toscrape.com/catalogue/page-13.html
Revisando: https://books.toscrape.com/catalogue/page-14.html
Revisando: https://books.toscrape.com/catalogue/page-15.html
Revisando: https://books.toscrape.com/catalogue/page-16.html
Revisando: https://books.toscrape.com/catalogue/page-17.html
Revisando: https://books.toscrape.com/catalogue/page-18.html
Revisando: https://books.toscrape.com/catalogue/page-19.html
Revisando: https://books.toscrape.com/catalogue/page-20.html
Revisando: https://books.toscrape.com/catalogue/page-21.html
Revisando: https://books.toscrape.com/catalogue/page-22.html
Revisando: https://books.toscrape.com/catalogue/page-23.html
Revisando: https://books.toscrape.com/catalogue/page-24.html
Revisando: https://books.toscrape.com/catalogue/page-25.html
Revisando: https://books.toscrape.com/catalogue/page-26.html
Revisando: https://books.toscrape.com/catalogue/page-27.html
Revisando: https://books.toscrape.com/catalogue/page-28.html
Revisando: https://books.toscrape.com/catalogue/page-29.html
Revisando: https://books.toscrape.com/catalogue/page-30.html
Revisando: https://books.toscrape.com/catalogue/page-31.html
Revisando: https://books.toscrape.com/catalogue/page-32.html
Revisando: https://books.toscrape.com/catalogue/page-33.html
Revisando: https://books.toscrape.com/catalogue/page-34.html
Revisando: https://books.toscrape.com/catalogue/page-35.html
Revisando: https://books.toscrape.com/catalogue/page-36.html
Revisando: https://books.toscrape.com/catalogue/page-37.html
Revisando: https://books.toscrape.com/catalogue/page-38.html
Revisando: https://books.toscrape.com/catalogue/page-39.html
Revisando: https://books.toscrape.com/catalogue/page-40.html
Revisando: https://books.toscrape.com/catalogue/page-41.html
Revisando: https://books.toscrape.com/catalogue/page-42.html
Revisando: https://books.toscrape.com/catalogue/page-43.html
Revisando: https://books.toscrape.com/catalogue/page-44.html
Revisando: https://books.toscrape.com/catalogue/page-45.html
Revisando: https://books.toscrape.com/catalogue/page-46.html
Revisando: https://books.toscrape.com/catalogue/page-47.html
Revisando: https://books.toscrape.com/catalogue/page-48.html
Revisando: https://books.toscrape.com/catalogue/page-49.html
Revisando: https://books.toscrape.com/catalogue/page-50.html

In [50]:
books_df.head()

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock (19 available),Aaron Ledbetter’s future had been planned out ...
1,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,17.66,5,Spirituality,In stock (18 available),"In The Four Agreements, don Miguel Ruiz reveal..."
2,6be3beb0793a53e7,Sophie's World,15.94,5,Philosophy,In stock (18 available),A page-turning novel that is also an explorati...
3,657fe5ead67a7767,Untitled Collection: Sabbath Poems 2014,14.27,4,Poetry,In stock (16 available),"More than thirty-five years ago, when the weat..."
4,51653ef291ab7ddc,This One Summer,19.49,4,Sequential Art,In stock (16 available),"Every summer, Rose goes with her mom and dad t..."

In [51]:
books_df.shape

(75, 7)

In [52]:
print("Libros con valoración inferior a 4:")
print(books_df.loc[books_df["Rating"] < 4])

print("\nLibros con precio superior a 20 £:")
print(books_df.loc[books_df["Price (£)"] > 20])

Libros con valoración inferior a 4:
Empty DataFrame
Columns: [UPC, Title, Price (£), Rating, Genre, Availability, Description]
Index: []

Libros con precio superior a 20 £:
Empty DataFrame
Columns: [UPC, Title, Price (£), Rating, Genre, Availability, Description]
Index: []

In [53]:
books_test_df = scrape_books(min_rating=5, max_price=15)

Revisando: https://books.toscrape.com/
Revisando: https://books.toscrape.com/catalogue/page-2.html
Revisando: https://books.toscrape.com/catalogue/page-3.html
Revisando: https://books.toscrape.com/catalogue/page-4.html
Revisando: https://books.toscrape.com/catalogue/page-5.html
Revisando: https://books.toscrape.com/catalogue/page-6.html
Revisando: https://books.toscrape.com/catalogue/page-7.html
Revisando: https://books.toscrape.com/catalogue/page-8.html
Revisando: https://books.toscrape.com/catalogue/page-9.html
Revisando: https://books.toscrape.com/catalogue/page-10.html
Revisando: https://books.toscrape.com/catalogue/page-11.html
Revisando: https://books.toscrape.com/catalogue/page-12.html
Revisando: https://books.toscrape.com/catalogue/page-13.html
Revisando: https://books.toscrape.com/catalogue/page-14.html
Revisando: https://books.toscrape.com/catalogue/page-15.html
Revisando: https://books.toscrape.com/catalogue/page-16.html
Revisando: https://books.toscrape.com/catalogue/page-17.html
Revisando: https://books.toscrape.com/catalogue/page-18.html
Revisando: https://books.toscrape.com/catalogue/page-19.html
Revisando: https://books.toscrape.com/catalogue/page-20.html
Revisando: https://books.toscrape.com/catalogue/page-21.html
Revisando: https://books.toscrape.com/catalogue/page-22.html
Revisando: https://books.toscrape.com/catalogue/page-23.html
Revisando: https://books.toscrape.com/catalogue/page-24.html
Revisando: https://books.toscrape.com/catalogue/page-25.html
Revisando: https://books.toscrape.com/catalogue/page-26.html
Revisando: https://books.toscrape.com/catalogue/page-27.html
Revisando: https://books.toscrape.com/catalogue/page-28.html
Revisando: https://books.toscrape.com/catalogue/page-29.html
Revisando: https://books.toscrape.com/catalogue/page-30.html
Revisando: https://books.toscrape.com/catalogue/page-31.html
Revisando: https://books.toscrape.com/catalogue/page-32.html
Revisando: https://books.toscrape.com/catalogue/page-33.html
Revisando: https://books.toscrape.com/catalogue/page-34.html
Revisando: https://books.toscrape.com/catalogue/page-35.html
Revisando: https://books.toscrape.com/catalogue/page-36.html
Revisando: https://books.toscrape.com/catalogue/page-37.html
Revisando: https://books.toscrape.com/catalogue/page-38.html
Revisando: https://books.toscrape.com/catalogue/page-39.html
Revisando: https://books.toscrape.com/catalogue/page-40.html
Revisando: https://books.toscrape.com/catalogue/page-41.html
Revisando: https://books.toscrape.com/catalogue/page-42.html
Revisando: https://books.toscrape.com/catalogue/page-43.html
Revisando: https://books.toscrape.com/catalogue/page-44.html
Revisando: https://books.toscrape.com/catalogue/page-45.html
Revisando: https://books.toscrape.com/catalogue/page-46.html
Revisando: https://books.toscrape.com/catalogue/page-47.html
Revisando: https://books.toscrape.com/catalogue/page-48.html
Revisando: https://books.toscrape.com/catalogue/page-49.html
Revisando: https://books.toscrape.com/catalogue/page-50.html

In [54]:
print("Filas y columnas:", books_test_df.shape)
print(books_test_df[["Title", "Price (£)", "Rating"]].head())

Filas y columnas: (23, 7)
                                               Title  Price (£)  Rating
0  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...      13.61       5
1   Princess Between Worlds (Wide-Awake Princess #5)      13.34       5
2  The Third Wave: An Entrepreneur’s Vision of th...      12.61       5
3                     Agnostic: A Spirited Manifesto      12.51       5
4                  Walt Disney's Alice in Wonderland      12.96       5